### ISSUE TITLE
[Question]will the DIRE part be released?

### ISSUE THREAD

**Issue by xianghang** [Jyonn/GENRE-requests#1]
Firstly, thanks so much for releasing the code. This work is very interesting and insightful.

It seems that the code only contains the GENRE part (i.e. prompting closed source LLMs), while the DIRE (i.e. finetuning the open source LLMs) is not included(?). Do you have future plan to release that part as well?

**Comment by Jyonn** [comment]
Thanks for your attention! We have released training codes [here](https://github.com/Jyonn/GNRS) without detailed guidance, but you can have a look at the implementation. The core code is the [LLMOperator](https://github.com/Jyonn/GNRS/blob/master/model/operator/llama_operator.py). We will prepare the guidance ASAP!

**Comment by xianghang** [comment]
Cool. Many thanks.
