### ISSUE TITLE
Question about Models Config Files

### ISSUE THREAD

**Issue by whonor** [Jyonn/GENRE-requests#10]
Hi there,

I have a question about model config files such as llama-naml.yml and bert-naml.yml. 
If I wanna use the ONCE framework to run NAML, which one I should select ?

Thanks.

**Comment by Jyonn** [comment]
Hi, please use `config/model/lego_naml.yaml` file.

**Comment by whonor** [comment]
Thank you for your responds. 

I follow other issues and suggestions, but I cannot reproduce paper's results.

This is my commands to run ONCE-NAML:

`python worker.py --embed config/embed/llama-token.yaml --model config/model/lego_naml.yaml --exp config/exp/tt-llm.yaml --data config/data/mind-llama.yaml --version small --llm_ver 7b --layer 0 --lora 0 --embed_hidden_size 4096 --hidden_size 256 --fast-eval 0 --page_size 4 --batch_size 32 --epoch_batch -4 --acc_batch 2 --lr 0.001 --item_lr 0.00001`

The results as follows:

GAUC: 0.6519
MRR: 0.3321
NDCG@5: 0.3441
NDCG@10: 0.4048


These results are too lower than yours.

Could you give me some suggestions?

Thanks.

**Comment by Jyonn** [comment]
Hi, I am not sure which baseline are you running. In your case, you use llama token representations, but apply CNN module proposed by NAML to encode item content. There is no corresponding baseline in our paper I guess.

**Comment by whonor** [comment]
Hi, I'm so confused how to reproduce these results in the paper:

![results](https://github.com/user-attachments/assets/000efa97-c3ee-48b1-ba85-eeca328db303)

Thanks.

**Comment by Jyonn** [comment]
Well, ONCE integrates DIRE (using Llama as item encoder) and GENRE (using ChatGPT for data augmentation).

Previously, I treat your your question, `If I wanna use the ONCE framework to run NAML, which one I should select ?`, as `How to run original NAML model using my code`, so I tell you to select `lego_naml.yaml`.

I suggest you to follow the [documentation](https://github.com/Jyonn/ONCE?tab=readme-ov-file#training-preparation-for-tuning-llama) here to firstly reproduce our DIRE-Llama7B-NAML model. Then, switch the data configuration from original dataset to GPT-augmented dataset.

**Comment by whonor** [comment]
Thank you so much.
