### ISSUE TITLE
Need Help。Where is the History Encoder

### ISSUE THREAD

**Issue by silent0610** [Jyonn/GENRE-requests#2]
Thank you very much for sharing.
i have to say i am a beginner.
I've looked at part of the GNRS code, but I still don't quite understand it. Please tell me where is the implementation of History Encoder?
Is there an additive attention mechanism in both History Encoder and Aention Fusion Layer?
Thanks again。

**Comment by Jyonn** [comment]
Hi, first, thanks for your attention to our efforts! Do you mean [GreenRec](https://github.com/Jyonn/GNRS)? If you have question about that repo, you can new issues there.

In this work (ONCE), we use newly designed Legommenders framework to train the models. If you have questions about it, please new issues in Legommenders.

Some history encoders (such as Attention) use additive attention module, but some are not. Attention Fusion Layer is equal to the additive attention module.


Thanks

**Comment by silent0610** [comment]
thanks
