### ISSUE TITLE
未预期的符号“newline”附近有语法错误

### ISSUE THREAD

**Issue by ghost** [Jyonn/GENRE-requests#3]
When I run this line of code, it will prompt an error message：

![image](https://github.com/Jyonn/ONCE/assets/117421898/a44625d6-d40a-4884-b0fd-89ae760a68b6)

(once) xgd@xgd-MS-7B94:~/home/xgd/lego$ python worker.py --embed config/embed/<embed>.yaml --model config/model/llama-naml.yaml --exp config/exp/llama-split.yaml
 --data config/data/mind-llama.yaml --version small --llm_ver <llm_ver> --hidden_size 64 --layer 0 --lora 0 --fast_eval 0 --embed_hidden_size <embed_hidden_size>

-bash: 未预期的符号“newline”附近有语法错误

I hope to receive your reply

**Comment by Jyonn** [comment]
> When I run this line of code, it will prompt an error message：
> 
> ![image](https://private-user-images.githubusercontent.com/117421898/300258490-a44625d6-d40a-4884-b0fd-89ae760a68b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDQ3MjksIm5iZiI6MTcwNjQ0NDQyOSwicGF0aCI6Ii8xMTc0MjE4OTgvMzAwMjU4NDkwLWE0NDYyNWQ2LWQ0MGEtNDg4NC1iMGZkLTg5YWU3NjBhNjhiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxMjIwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzVkZGQ3MTIzNmRiOTllYmMyZTA0ODhhYzY1ZDAyN2MyNTczZDEwYjVlZjk4OWE2MjAzNjEwNjlkMWY1YTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hg2EYftg5ZC3PKkYe7VlwPp7WHsEZpS7FlJlZVslCMw)
> 
> (once) xgd@xgd-MS-7B94:~/home/xgd/lego$ python worker.py --embed config/embed/.yaml --model config/model/llama-naml.yaml --exp config/exp/llama-split.yaml --data config/data/mind-llama.yaml --version small --llm_ver <llm_ver> --hidden_size 64 --layer 0 --lora 0 --fast_eval 0 --embed_hidden_size <embed_hidden_size>
> 
> -bash: 未预期的符号“newline”附近有语法错误
> 
> I hope to receive your reply

Hi, thanks for your attention to our work.

You need to specify the all the parameters like <llm_ver>. Feel free to ask if you meet further questions.
