### ISSUE TITLE
How to reproduce the dataset from original dataset?

### ISSUE THREAD

**Issue by Zegelink** [Jyonn/GENRE-requests#8]
Hello dear authors,

Thank you for sharing your work and publishing the dataset! I am currently making some modifications, and it would be very helpful if you could share the code you used to produce the shared dataset from the original sources, such as MIND-SMALL and Goodreads.

Best regards,
Ze

**Comment by Jyonn** [comment]
Hi, please refer to [here](https://github.com/Jyonn/Legommenders/tree/master/process) for dataset preprocessing.

**Comment by liyucheng09** [comment]
Hi Qijiong,

Can you confirm how can we reproduce the goodreads `train/val/test` as used in https://github.com/Jyonn/Legommenders/blob/32dd8334ee20e57f10cff3e04e8ed4e871730759/processor/goodreads_processor.py#L136.

**Comment by Jyonn** [comment]
No. This is new processor for the Goodreads dataset.

**Comment by Jyonn** [comment]
Please use released `v1-final` to run the preprocessing script.

**Comment by liyucheng09** [comment]
@Jyonn Hi Qijiong, can I ask what is `v1-final` here?

**Comment by Jyonn** [comment]
Hi, please visit this [link](https://github.com/Jyonn/Legommenders/releases/tag/v1).

**Comment by Jyonn** [comment]
Due to the upgrade of Legommenders, you can either download the source code of [v1-final](https://github.com/Jyonn/Legommenders/releases/tag/v1) or visit [here](https://github.com/Jyonn/Legommenders/tree/v1) to preprocess the data by yourselves.

**Comment by liyucheng09** [comment]
@Jyonn thanks for your response! I tries to use Legommenders:

```
(once) (base) yucheni@80a9972f6efa Legommenders % python process.py --data goodreads
/Users/yucheni/projects/Legommenders/utils/config_init.py:49: UserWarning: config file .data not found
  warnings.warn(f'config file .{cls.classname()} not found')
example .data config:
mind = /path/to/mind
goodreads = /path/to/goodreads
Traceback (most recent call last):
  File "/Users/yucheni/projects/Legommenders/process.py", line 41, in <module>
    data_dir = DataInit.get(args.data)
  File "/Users/yucheni/projects/Legommenders/utils/config_init.py", line 71, in get
    raise ValueError(f'key {key} not found in config')
ValueError: key goodreads not found in config
```

So not sure what's the issue here. I also tried:

```
(once) (base) yucheni@80a9972f6efa Legommenders % python process.py --data mind     
/Users/yucheni/projects/Legommenders/utils/config_init.py:49: UserWarning: config file .data not found
  warnings.warn(f'config file .{cls.classname()} not found')
example .data config:
mind = /path/to/mind
goodreads = /path/to/goodreads
Traceback (most recent call last):
  File "/Users/yucheni/projects/Legommenders/process.py", line 41, in <module>
    data_dir = DataInit.get(args.data)
  File "/Users/yucheni/projects/Legommenders/utils/config_init.py", line 71, in get
    raise ValueError(f'key {key} not found in config')
ValueError: key mind not found in config
```

Same issue. Not sure what's the problem here.

**Comment by Jyonn** [comment]
I will response within three days. I am currently rushing for a conference paper.
