### ISSUE TITLE
llama-token.npy issue

### ISSUE THREAD

**Issue by nemesisXX** [Jyonn/GENRE-requests#9]
Hello,
we try to replicate the ONCE experiment and start with the training preparation part. However, when we ran the worker.py, we realized we didn't have a llama-token.npy file. We have detected the tokenized dataset, and there's no file called llama-token.npy as well. Is there any doc missing here? Or is there any python files that could help us generate llama-token.npy? thank you.

**Comment by Jyonn** [comment]
Please refer to [here](https://github.com/Jyonn/Legommenders/issues/11) for the token embedding generation.
